# Generated by Django 4.1.1 on 2022-10-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitetoevent",
            name="status",
            field=models.CharField(
                choices=[("Accepted", "Accepted"), ("Declined", "Declined")],
                default=None,
                max_length=10,
            ),
        ),
    ]
