# Generated by Django 4.1.1 on 2022-10-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_invitetoevent_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitetoevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("Waiting", "Waiting"),
                    ("Accepted", "Accepted"),
                    ("Declined", "Declined"),
                ],
                default="Waiting",
                max_length=10,
            ),
        ),
    ]
