# Generated by Django 4.1.1 on 2022-11-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_alter_requesttoparticipation_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="gender",
            field=models.CharField(
                choices=[("Man", "Man"), ("Woman", "Woman")], max_length=10
            ),
        ),
    ]
