# Generated by Django 4.1.1 on 2022-11-03 17:39

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_alter_code_dop_info_alter_code_life_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                null=True,
                upload_to=authentication.models.image_file_name,
                validators=[authentication.models.validate_image],
            ),
        ),
    ]
